# Generated by Django 5.0 on 2024-07-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='Dept_name',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
    ]
