# Generated by Django 5.0 on 2024-07-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_profile', '0002_rename_name_department_dept_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Dept_name',
            new_name='dept_name',
        ),
    ]
