# Generated by Django 5.0 on 2024-07-09 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('department_name', models.CharField(max_length=100)),
                ('semester_name', models.CharField(max_length=50)),
                ('batch_number', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('marks', models.IntegerField()),
                ('q1_number', models.IntegerField()),
                ('q1_description', models.TextField()),
                ('q1_marks', models.IntegerField()),
                ('q2_number', models.IntegerField()),
                ('q2_description', models.TextField()),
                ('q2_marks', models.IntegerField()),
                ('q3_number', models.IntegerField()),
                ('q3_description', models.TextField()),
                ('q3_marks', models.IntegerField()),
                ('q4_number', models.IntegerField()),
                ('q4_description', models.TextField()),
                ('q4_marks', models.IntegerField()),
                ('q5_number', models.IntegerField()),
                ('q5_description', models.TextField()),
                ('q5_marks', models.IntegerField()),
                ('q6_number', models.IntegerField()),
                ('q6_description', models.TextField()),
                ('q6_marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
                ('marks', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.exam')),
            ],
        ),
    ]
