# Generated by Django 5.0 on 2024-07-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_exam_batch_number_alter_exam_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
