# Generated by Django 5.0 on 2024-07-10 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatplan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='roll',
        ),
        migrations.AddField(
            model_name='column',
            name='column_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_columns',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='student',
            name='intake',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='seatplan.intake'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='number_of_seats',
            field=models.IntegerField(default=40),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seatplan.column')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seatplan.student')),
            ],
        ),
    ]
