# Generated by Django 5.0 on 2024-07-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatplan', '0003_remove_seat_column_remove_seat_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
