# Generated by Django 5.0 on 2024-07-10 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seatplan', '0005_rename_columns_room_num_columns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='intake',
        ),
        migrations.DeleteModel(
            name='SeatPlan',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
