# Generated by Django 5.0 on 2024-07-10 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatplan', '0006_remove_student_intake_delete_seatplan_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=100, unique=True)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seatplan.intake')),
            ],
        ),
        migrations.CreateModel(
            name='SeatPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.IntegerField()),
                ('seat_number', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seatplan.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seatplan.student')),
            ],
            options={
                'unique_together': {('room', 'column', 'seat_number')},
            },
        ),
    ]
